---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower
  - yarn --version
  - bower --version

install:
  - yarn install
  - bower install

script:
  - yarn run nodetest