---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  yarn: true

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm config set spin false
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower
  - yarn --version
  - bower --version

install:
  - yarn install
  - bower install

script:
  - yarn run nodetest
  - yarn run fastboottest